flags: {}
packages:
- '.'
extra-deps:
- base-orphans-0.4.1
- bindings-GLFW-3.1.1.3
- monad-skeleton-0.1.2.1
- monad-stm-0.1.0.2
- witherable-0.1.3
- GLFW-b-1.4.7.2
- JuicyPixels-util-0.2
- WAVE-0.1.3
- audiovisual-0.0
- bindings-portaudio-0.1
- colors-0.3.0.2
- control-bool-0.2.1
- freetype2-0.1.1
- objective-1.0.5
- KdTree-0.2.1
- boundingboxes-0.2.3
- call-0.2
resolver: lts-2.18
